# -*- coding: utf-8 -*-
"""Clase1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3NIVZunU1ur3Nxzwhej99dzXuF55mMP

# **Arrays en NumPy**
"""

import numpy as np
escalar = np.array(42)
print(escalar)

vector = np.array([30,29,35,31,36,28,27])
print(vector)

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

tensor = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(tensor)

array_arange = np.arange(10)
print(array_arange)

eye_matrix = np.eye(3)
print(eye_matrix)

diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

random = np.random.random((2,3))
print(random)